/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.async.RequestHandler;
import org.example.async.RequestHandlerFactory;

import java.io.*;
import java.net.Socket;

public class App {
    public String getGreeting() {
        return "Hello My-Redis World!";
    }

    private static final int PORT = 9000;

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        RequestHandler requestHandler = RequestHandlerFactory.getHandler();
        requestHandler.handleRequests();
    }
}
